### ISSUE TITLE
slow as fuck

### ISSUE THREAD

**Issue by DjAdolf** [skwig/ShitpostBot#19]
pls check v utery thank you si
![abbachio](https://user-images.githubusercontent.com/101047602/156922645-9c6df614-0fd3-40c5-817d-cd4add7aede1.jpg)
r

**Comment by TvojeMater** [comment]
+rep

**Comment by DjAdolf** [comment]
:trollface:

**Comment by skwig** [comment]
WONTFIX

**Comment by skwig** [comment]
WONTFIX
